/* tslint:disable */
/* eslint-disable */
/**
 * TempoGeoPolitical Map RESTful API
 * API for querying historical political events and metadata filter values.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface BasicErrorObjectDef
 */
export interface BasicErrorObjectDef {
    /**
     * 
     * @type {string}
     * @memberof BasicErrorObjectDef
     */
    'id'?: string;
    /**
     * An application-specific error code, expressed as a string value.
     * @type {number}
     * @memberof BasicErrorObjectDef
     */
    'code'?: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof BasicErrorObjectDef
     */
    'detail'?: string;
    /**
     * An object containing references to the source of the error.
     * @type {string}
     * @memberof BasicErrorObjectDef
     */
    'source'?: string;
}
/**
 * Metadata entry for a country code filter value.
 * @export
 * @interface CountryCodeMetadataItemDef
 */
export interface CountryCodeMetadataItemDef {
    /**
     * ISO 3166-1 alpha-3 country code (3 uppercase letters).
     * @type {string}
     * @memberof CountryCodeMetadataItemDef
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof CountryCodeMetadataItemDef
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface CountryCodeMetadataListResponseBodyDef
 */
export interface CountryCodeMetadataListResponseBodyDef {
    /**
     * 
     * @type {Array<CountryCodeMetadataItemDef>}
     * @memberof CountryCodeMetadataListResponseBodyDef
     */
    'data': Array<CountryCodeMetadataItemDef>;
    /**
     * 
     * @type {PaginationDef}
     * @memberof CountryCodeMetadataListResponseBodyDef
     */
    'pagination': PaginationDef;
}
/**
 * Information about a Country related to the Event.
 * @export
 * @interface CountryDef
 */
export interface CountryDef {
    /**
     * 
     * @type {string}
     * @memberof CountryDef
     */
    'wikidataId': string;
    /**
     * 
     * @type {string}
     * @memberof CountryDef
     */
    'name': string;
}
/**
 * List of Countries related to the Event.
 * @export
 * @interface CountryListDef
 */
export interface CountryListDef extends Array<CountryDef> {
}
/**
 * 
 * @export
 * @interface Error400Def
 */
export interface Error400Def {
    /**
     * 
     * @type {string}
     * @memberof Error400Def
     */
    'id'?: string;
    /**
     * An application-specific error code, expressed as a string value.
     * @type {number}
     * @memberof Error400Def
     */
    'code'?: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof Error400Def
     */
    'detail'?: string;
    /**
     * An object containing references to the source of the error.
     * @type {string}
     * @memberof Error400Def
     */
    'source'?: string;
    /**
     * 
     * @type {any}
     * @memberof Error400Def
     */
    'status'?: any;
    /**
     * 
     * @type {any}
     * @memberof Error400Def
     */
    'title'?: any;
}
/**
 * 
 * @export
 * @interface Error401Def
 */
export interface Error401Def {
    /**
     * 
     * @type {string}
     * @memberof Error401Def
     */
    'id'?: string;
    /**
     * An application-specific error code, expressed as a string value.
     * @type {number}
     * @memberof Error401Def
     */
    'code'?: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof Error401Def
     */
    'detail'?: string;
    /**
     * An object containing references to the source of the error.
     * @type {string}
     * @memberof Error401Def
     */
    'source'?: string;
    /**
     * 
     * @type {any}
     * @memberof Error401Def
     */
    'status'?: any;
    /**
     * 
     * @type {any}
     * @memberof Error401Def
     */
    'title'?: any;
}
/**
 * 
 * @export
 * @interface Error403Def
 */
export interface Error403Def {
    /**
     * 
     * @type {string}
     * @memberof Error403Def
     */
    'id'?: string;
    /**
     * An application-specific error code, expressed as a string value.
     * @type {number}
     * @memberof Error403Def
     */
    'code'?: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof Error403Def
     */
    'detail'?: string;
    /**
     * An object containing references to the source of the error.
     * @type {string}
     * @memberof Error403Def
     */
    'source'?: string;
    /**
     * 
     * @type {any}
     * @memberof Error403Def
     */
    'status'?: any;
    /**
     * 
     * @type {any}
     * @memberof Error403Def
     */
    'title'?: any;
}
/**
 * 
 * @export
 * @interface Error404Def
 */
export interface Error404Def {
    /**
     * 
     * @type {string}
     * @memberof Error404Def
     */
    'id'?: string;
    /**
     * An application-specific error code, expressed as a string value.
     * @type {number}
     * @memberof Error404Def
     */
    'code'?: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof Error404Def
     */
    'detail'?: string;
    /**
     * An object containing references to the source of the error.
     * @type {string}
     * @memberof Error404Def
     */
    'source'?: string;
    /**
     * 
     * @type {any}
     * @memberof Error404Def
     */
    'status'?: any;
    /**
     * 
     * @type {any}
     * @memberof Error404Def
     */
    'title'?: any;
}
/**
 * 
 * @export
 * @interface Error406Def
 */
export interface Error406Def {
    /**
     * 
     * @type {string}
     * @memberof Error406Def
     */
    'id'?: string;
    /**
     * An application-specific error code, expressed as a string value.
     * @type {number}
     * @memberof Error406Def
     */
    'code'?: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof Error406Def
     */
    'detail'?: string;
    /**
     * An object containing references to the source of the error.
     * @type {string}
     * @memberof Error406Def
     */
    'source'?: string;
    /**
     * 
     * @type {any}
     * @memberof Error406Def
     */
    'status'?: any;
    /**
     * 
     * @type {any}
     * @memberof Error406Def
     */
    'title'?: any;
}
/**
 * 
 * @export
 * @interface Error429Def
 */
export interface Error429Def {
    /**
     * 
     * @type {string}
     * @memberof Error429Def
     */
    'id'?: string;
    /**
     * An application-specific error code, expressed as a string value.
     * @type {number}
     * @memberof Error429Def
     */
    'code'?: number;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof Error429Def
     */
    'detail'?: string;
    /**
     * An object containing references to the source of the error.
     * @type {string}
     * @memberof Error429Def
     */
    'source'?: string;
    /**
     * 
     * @type {any}
     * @memberof Error429Def
     */
    'status'?: any;
    /**
     * 
     * @type {any}
     * @memberof Error429Def
     */
    'title'?: any;
}
/**
 * Historical political Event.
 * @export
 * @interface EventDef
 */
export interface EventDef {
    /**
     * 
     * @type {EventTypeDef}
     * @memberof EventDef
     */
    'type': EventTypeDef;
    /**
     * Wikidata entity ID (e.g., Q178810).
     * @type {string}
     * @memberof EventDef
     */
    'wikidataId': string;
    /**
     * URL of the corresponding Wikidata item.
     * @type {string}
     * @memberof EventDef
     */
    'wikidataUrl': string;
    /**
     * Name of a historical political Event.
     * @type {string}
     * @memberof EventDef
     */
    'name': string;
    /**
     * Detailed information about a historical political Event.
     * @type {string}
     * @memberof EventDef
     */
    'description'?: string;
    /**
     * URL of the corresponding Wikipedia article.
     * @type {string}
     * @memberof EventDef
     */
    'wikipediaUrl'?: string;
    /**
     * URL of an image representing the event.
     * @type {string}
     * @memberof EventDef
     */
    'imageUrl'?: string;
    /**
     * 
     * @type {RegionListDef}
     * @memberof EventDef
     */
    'regions'?: RegionListDef;
    /**
     * 
     * @type {CountryListDef}
     * @memberof EventDef
     */
    'countries'?: CountryListDef;
    /**
     * 
     * @type {LocationListDef}
     * @memberof EventDef
     */
    'locations'?: LocationListDef;
    /**
     * 
     * @type {EventTimeStateRelativeToNowDef}
     * @memberof EventDef
     */
    'timeStateRelativeToNow': EventTimeStateRelativeToNowDef;
    /**
     * Event timestamp in UTC using ISO 8601 date-time format.
     * @type {string}
     * @memberof EventDef
     */
    'startDateTime': string;
    /**
     * Event timestamp in UTC using ISO 8601 date-time format.
     * @type {string}
     * @memberof EventDef
     */
    'endDateTime'?: string;
}


/**
 * 
 * @export
 * @interface EventListResponseBodyDef
 */
export interface EventListResponseBodyDef {
    /**
     * 
     * @type {Array<EventDef>}
     * @memberof EventListResponseBodyDef
     */
    'data': Array<EventDef>;
    /**
     * 
     * @type {PaginationDef}
     * @memberof EventListResponseBodyDef
     */
    'pagination': PaginationDef;
}
/**
 * Indicates whether event is in past, happens now or will occur in future.
 * @export
 * @enum {string}
 */

export const EventTimeStateRelativeToNowDef = {
    PAST: 'PAST',
    ONGOING: 'ONGOING',
    FUTURE: 'FUTURE'
} as const;

export type EventTimeStateRelativeToNowDef = typeof EventTimeStateRelativeToNowDef[keyof typeof EventTimeStateRelativeToNowDef];


/**
 * Type of an Event.
 * @export
 * @enum {string}
 */

export const EventTypeDef = {
    GEOPOLITICAL_GROUP: 'GEOPOLITICAL_GROUP',
    INTERNATIONAL_ORGANISATION: 'INTERNATIONAL_ORGANISATION',
    MILITARY_ALLIANCE: 'MILITARY_ALLIANCE',
    MULTINATIONAL_MILITARY_COALITION: 'MULTINATIONAL_MILITARY_COALITION',
    POLITICAL_CONFERENCE: 'POLITICAL_CONFERENCE',
    POLITICAL_CRISIS: 'POLITICAL_CRISIS',
    POLITICAL_MURDER: 'POLITICAL_MURDER',
    SOURCE_OF_INTERNATIONAL_LAW: 'SOURCE_OF_INTERNATIONAL_LAW',
    SUPRANATIONAL_UNION: 'SUPRANATIONAL_UNION',
    WARFARE_AND_ARMED_CONFLICTS: 'WARFARE_AND_ARMED_CONFLICTS'
} as const;

export type EventTypeDef = typeof EventTypeDef[keyof typeof EventTypeDef];


/**
 * Metadata entry for an event type filter value.
 * @export
 * @interface EventTypeMetadataItemDef
 */
export interface EventTypeMetadataItemDef {
    /**
     * 
     * @type {EventTypeDef}
     * @memberof EventTypeMetadataItemDef
     */
    'code': EventTypeDef;
    /**
     * 
     * @type {string}
     * @memberof EventTypeMetadataItemDef
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof EventTypeMetadataItemDef
     */
    'description': string;
}


/**
 * 
 * @export
 * @interface EventTypeMetadataListResponseBodyDef
 */
export interface EventTypeMetadataListResponseBodyDef {
    /**
     * 
     * @type {Array<EventTypeMetadataItemDef>}
     * @memberof EventTypeMetadataListResponseBodyDef
     */
    'data': Array<EventTypeMetadataItemDef>;
}
/**
 * Information about a Location related to the Event.
 * @export
 * @interface LocationDef
 */
export interface LocationDef {
    /**
     * 
     * @type {string}
     * @memberof LocationDef
     */
    'wikidataId': string;
    /**
     * 
     * @type {string}
     * @memberof LocationDef
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof LocationDef
     */
    'coordinate': string;
}
/**
 * List of Locations related to the Event.
 * @export
 * @interface LocationListDef
 */
export interface LocationListDef extends Array<LocationDef> {
}
/**
 * Pagination metadata for list responses.
 * @export
 * @interface PaginationDef
 */
export interface PaginationDef {
    /**
     * 
     * @type {number}
     * @memberof PaginationDef
     */
    'page': number;
    /**
     * 
     * @type {number}
     * @memberof PaginationDef
     */
    'pageSize': number;
    /**
     * 
     * @type {number}
     * @memberof PaginationDef
     */
    'totalItems': number;
    /**
     * 
     * @type {number}
     * @memberof PaginationDef
     */
    'totalPages': number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginationDef
     */
    'hasNextPage': boolean;
}
/**
 * World Region.
 * @export
 * @enum {string}
 */

export const RegionDef = {
    EAST_ASIA_AND_PACIFIC: 'EAST_ASIA_AND_PACIFIC',
    EUROPE_AND_CENTRAL_ASIA: 'EUROPE_AND_CENTRAL_ASIA',
    LATIN_AMERICA_AND_CARIBBEAN: 'LATIN_AMERICA_AND_CARIBBEAN',
    MIDDLE_EAST_AND_NORTH_AFRICA: 'MIDDLE_EAST_AND_NORTH_AFRICA',
    NORTH_AMERICA: 'NORTH_AMERICA',
    SOUTH_ASIA: 'SOUTH_ASIA',
    SUB_SAHARAN_AFRICA: 'SUB_SAHARAN_AFRICA'
} as const;

export type RegionDef = typeof RegionDef[keyof typeof RegionDef];


/**
 * List of World Regions to filter Events.
 * @export
 * @interface RegionListDef
 */
export interface RegionListDef extends Array<RegionDef> {
}
/**
 * Metadata entry for a region filter value.
 * @export
 * @interface RegionMetadataItemDef
 */
export interface RegionMetadataItemDef {
    /**
     * 
     * @type {RegionDef}
     * @memberof RegionMetadataItemDef
     */
    'code': RegionDef;
    /**
     * 
     * @type {string}
     * @memberof RegionMetadataItemDef
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof RegionMetadataItemDef
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof RegionMetadataItemDef
     */
    'displayOrder'?: number;
    /**
     * 
     * @type {string}
     * @memberof RegionMetadataItemDef
     */
    'parentCode'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof RegionMetadataItemDef
     */
    'aliases'?: Array<string>;
}


/**
 * 
 * @export
 * @interface RegionMetadataListResponseBodyDef
 */
export interface RegionMetadataListResponseBodyDef {
    /**
     * 
     * @type {Array<RegionMetadataItemDef>}
     * @memberof RegionMetadataListResponseBodyDef
     */
    'data': Array<RegionMetadataItemDef>;
}

/**
 * EventsApi - axios parameter creator
 * @export
 */
export const EventsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a paginated list of historical political events filtered by type, region, country, and time range.
         * @summary List of Historical Political Events.
         * @param {string} [accept] Default accept header
         * @param {number} [page] Page number (1-based index).
         * @param {number} [pageSize] Number of items per page.
         * @param {Array<EventTypeDef>} [types] Type(s) of an Event:&lt;br&gt; &lt;ul&gt; &lt;li&gt;&#x60;GEOPOLITICAL_GROUP&#x60; - Political grouping of states with shared geopolitical interests.&lt;/li&gt; &lt;li&gt;&#x60;INTERNATIONAL_ORGANISATION&#x60; - Intergovernmental organisation operating across multiple countries.&lt;/li&gt; &lt;li&gt;&#x60;MILITARY_ALLIANCE&#x60; - Formal military alliance between states.&lt;/li&gt; &lt;li&gt;&#x60;MULTINATIONAL_MILITARY_COALITION&#x60; - Coalition of multiple countries formed for military operations.&lt;/li&gt; &lt;li&gt;&#x60;POLITICAL_CONFERENCE&#x60; - Formal political conference involving state or institutional actors.&lt;/li&gt; &lt;li&gt;&#x60;POLITICAL_CRISIS&#x60; - Significant political instability or confrontation.&lt;/li&gt; &lt;li&gt;&#x60;POLITICAL_MURDER&#x60; - Politically motivated assassination or killing.&lt;/li&gt; &lt;li&gt;&#x60;SOURCE_OF_INTERNATIONAL_LAW&#x60; - Treaty, convention, or other recognised source of international law.&lt;/li&gt; &lt;li&gt;&#x60;SUPRANATIONAL_UNION&#x60; - Union in which member states delegate authority to shared institutions.&lt;/li&gt; &lt;li&gt;&#x60;WARFARE_AND_ARMED_CONFLICTS&#x60; - Armed hostilities, military operations, and violent conflict between organised actors.&lt;/li&gt; &lt;/ul&gt;
         * @param {Array<RegionDef>} [regions] World Regions.&lt;br&gt; &lt;ul&gt; &lt;li&gt;&#x60;EAST_ASIA_AND_PACIFIC&#x60;&lt;/li&gt; &lt;li&gt;&#x60;EUROPE_AND_CENTRAL_ASIA&#x60;&lt;/li&gt; &lt;li&gt;&#x60;LATIN_AMERICA_AND_CARIBBEAN&#x60;&lt;/li&gt; &lt;li&gt;&#x60;MIDDLE_EAST_AND_NORTH_AFRICA&#x60;&lt;/li&gt; &lt;li&gt;&#x60;NORTH_AMERICA&#x60;&lt;/li&gt; &lt;li&gt;&#x60;SOUTH_ASIA&#x60;&lt;/li&gt; &lt;li&gt;&#x60;SUB_SAHARAN_AFRICA&#x60;&lt;/li&gt; &lt;/ul&gt;
         * @param {Array<string>} [countries] Country code(s) to filter Events by.
         * @param {string} [timeslotStart] Timeslot start date-time in UTC (ISO 8601) to filter by.
         * @param {string} [timeslotEnd] Timeslot end date-time in UTC (ISO 8601) to filter by.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2EventsGet: async (accept?: string, page?: number, pageSize?: number, types?: Array<EventTypeDef>, regions?: Array<RegionDef>, countries?: Array<string>, timeslotStart?: string, timeslotEnd?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (types) {
                localVarQueryParameter['types'] = types.join(COLLECTION_FORMATS.csv);
            }

            if (regions) {
                localVarQueryParameter['regions'] = regions.join(COLLECTION_FORMATS.csv);
            }

            if (countries) {
                localVarQueryParameter['countries'] = countries.join(COLLECTION_FORMATS.csv);
            }

            if (timeslotStart !== undefined) {
                localVarQueryParameter['timeslot_start'] = (timeslotStart as any instanceof Date) ?
                    (timeslotStart as any).toISOString() :
                    timeslotStart;
            }

            if (timeslotEnd !== undefined) {
                localVarQueryParameter['timeslot_end'] = (timeslotEnd as any instanceof Date) ?
                    (timeslotEnd as any).toISOString() :
                    timeslotEnd;
            }

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EventsApi - functional programming interface
 * @export
 */
export const EventsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EventsApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a paginated list of historical political events filtered by type, region, country, and time range.
         * @summary List of Historical Political Events.
         * @param {string} [accept] Default accept header
         * @param {number} [page] Page number (1-based index).
         * @param {number} [pageSize] Number of items per page.
         * @param {Array<EventTypeDef>} [types] Type(s) of an Event:&lt;br&gt; &lt;ul&gt; &lt;li&gt;&#x60;GEOPOLITICAL_GROUP&#x60; - Political grouping of states with shared geopolitical interests.&lt;/li&gt; &lt;li&gt;&#x60;INTERNATIONAL_ORGANISATION&#x60; - Intergovernmental organisation operating across multiple countries.&lt;/li&gt; &lt;li&gt;&#x60;MILITARY_ALLIANCE&#x60; - Formal military alliance between states.&lt;/li&gt; &lt;li&gt;&#x60;MULTINATIONAL_MILITARY_COALITION&#x60; - Coalition of multiple countries formed for military operations.&lt;/li&gt; &lt;li&gt;&#x60;POLITICAL_CONFERENCE&#x60; - Formal political conference involving state or institutional actors.&lt;/li&gt; &lt;li&gt;&#x60;POLITICAL_CRISIS&#x60; - Significant political instability or confrontation.&lt;/li&gt; &lt;li&gt;&#x60;POLITICAL_MURDER&#x60; - Politically motivated assassination or killing.&lt;/li&gt; &lt;li&gt;&#x60;SOURCE_OF_INTERNATIONAL_LAW&#x60; - Treaty, convention, or other recognised source of international law.&lt;/li&gt; &lt;li&gt;&#x60;SUPRANATIONAL_UNION&#x60; - Union in which member states delegate authority to shared institutions.&lt;/li&gt; &lt;li&gt;&#x60;WARFARE_AND_ARMED_CONFLICTS&#x60; - Armed hostilities, military operations, and violent conflict between organised actors.&lt;/li&gt; &lt;/ul&gt;
         * @param {Array<RegionDef>} [regions] World Regions.&lt;br&gt; &lt;ul&gt; &lt;li&gt;&#x60;EAST_ASIA_AND_PACIFIC&#x60;&lt;/li&gt; &lt;li&gt;&#x60;EUROPE_AND_CENTRAL_ASIA&#x60;&lt;/li&gt; &lt;li&gt;&#x60;LATIN_AMERICA_AND_CARIBBEAN&#x60;&lt;/li&gt; &lt;li&gt;&#x60;MIDDLE_EAST_AND_NORTH_AFRICA&#x60;&lt;/li&gt; &lt;li&gt;&#x60;NORTH_AMERICA&#x60;&lt;/li&gt; &lt;li&gt;&#x60;SOUTH_ASIA&#x60;&lt;/li&gt; &lt;li&gt;&#x60;SUB_SAHARAN_AFRICA&#x60;&lt;/li&gt; &lt;/ul&gt;
         * @param {Array<string>} [countries] Country code(s) to filter Events by.
         * @param {string} [timeslotStart] Timeslot start date-time in UTC (ISO 8601) to filter by.
         * @param {string} [timeslotEnd] Timeslot end date-time in UTC (ISO 8601) to filter by.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2EventsGet(accept?: string, page?: number, pageSize?: number, types?: Array<EventTypeDef>, regions?: Array<RegionDef>, countries?: Array<string>, timeslotStart?: string, timeslotEnd?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventListResponseBodyDef>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v2EventsGet(accept, page, pageSize, types, regions, countries, timeslotStart, timeslotEnd, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EventsApi.v2EventsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EventsApi - factory interface
 * @export
 */
export const EventsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EventsApiFp(configuration)
    return {
        /**
         * Returns a paginated list of historical political events filtered by type, region, country, and time range.
         * @summary List of Historical Political Events.
         * @param {EventsApiV2EventsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2EventsGet(requestParameters: EventsApiV2EventsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<EventListResponseBodyDef> {
            return localVarFp.v2EventsGet(requestParameters.accept, requestParameters.page, requestParameters.pageSize, requestParameters.types, requestParameters.regions, requestParameters.countries, requestParameters.timeslotStart, requestParameters.timeslotEnd, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for v2EventsGet operation in EventsApi.
 * @export
 * @interface EventsApiV2EventsGetRequest
 */
export interface EventsApiV2EventsGetRequest {
    /**
     * Default accept header
     * @type {string}
     * @memberof EventsApiV2EventsGet
     */
    readonly accept?: string

    /**
     * Page number (1-based index).
     * @type {number}
     * @memberof EventsApiV2EventsGet
     */
    readonly page?: number

    /**
     * Number of items per page.
     * @type {number}
     * @memberof EventsApiV2EventsGet
     */
    readonly pageSize?: number

    /**
     * Type(s) of an Event:&lt;br&gt; &lt;ul&gt; &lt;li&gt;&#x60;GEOPOLITICAL_GROUP&#x60; - Political grouping of states with shared geopolitical interests.&lt;/li&gt; &lt;li&gt;&#x60;INTERNATIONAL_ORGANISATION&#x60; - Intergovernmental organisation operating across multiple countries.&lt;/li&gt; &lt;li&gt;&#x60;MILITARY_ALLIANCE&#x60; - Formal military alliance between states.&lt;/li&gt; &lt;li&gt;&#x60;MULTINATIONAL_MILITARY_COALITION&#x60; - Coalition of multiple countries formed for military operations.&lt;/li&gt; &lt;li&gt;&#x60;POLITICAL_CONFERENCE&#x60; - Formal political conference involving state or institutional actors.&lt;/li&gt; &lt;li&gt;&#x60;POLITICAL_CRISIS&#x60; - Significant political instability or confrontation.&lt;/li&gt; &lt;li&gt;&#x60;POLITICAL_MURDER&#x60; - Politically motivated assassination or killing.&lt;/li&gt; &lt;li&gt;&#x60;SOURCE_OF_INTERNATIONAL_LAW&#x60; - Treaty, convention, or other recognised source of international law.&lt;/li&gt; &lt;li&gt;&#x60;SUPRANATIONAL_UNION&#x60; - Union in which member states delegate authority to shared institutions.&lt;/li&gt; &lt;li&gt;&#x60;WARFARE_AND_ARMED_CONFLICTS&#x60; - Armed hostilities, military operations, and violent conflict between organised actors.&lt;/li&gt; &lt;/ul&gt;
     * @type {Array<EventTypeDef>}
     * @memberof EventsApiV2EventsGet
     */
    readonly types?: Array<EventTypeDef>

    /**
     * World Regions.&lt;br&gt; &lt;ul&gt; &lt;li&gt;&#x60;EAST_ASIA_AND_PACIFIC&#x60;&lt;/li&gt; &lt;li&gt;&#x60;EUROPE_AND_CENTRAL_ASIA&#x60;&lt;/li&gt; &lt;li&gt;&#x60;LATIN_AMERICA_AND_CARIBBEAN&#x60;&lt;/li&gt; &lt;li&gt;&#x60;MIDDLE_EAST_AND_NORTH_AFRICA&#x60;&lt;/li&gt; &lt;li&gt;&#x60;NORTH_AMERICA&#x60;&lt;/li&gt; &lt;li&gt;&#x60;SOUTH_ASIA&#x60;&lt;/li&gt; &lt;li&gt;&#x60;SUB_SAHARAN_AFRICA&#x60;&lt;/li&gt; &lt;/ul&gt;
     * @type {Array<RegionDef>}
     * @memberof EventsApiV2EventsGet
     */
    readonly regions?: Array<RegionDef>

    /**
     * Country code(s) to filter Events by.
     * @type {Array<string>}
     * @memberof EventsApiV2EventsGet
     */
    readonly countries?: Array<string>

    /**
     * Timeslot start date-time in UTC (ISO 8601) to filter by.
     * @type {string}
     * @memberof EventsApiV2EventsGet
     */
    readonly timeslotStart?: string

    /**
     * Timeslot end date-time in UTC (ISO 8601) to filter by.
     * @type {string}
     * @memberof EventsApiV2EventsGet
     */
    readonly timeslotEnd?: string
}

/**
 * EventsApi - object-oriented interface
 * @export
 * @class EventsApi
 * @extends {BaseAPI}
 */
export class EventsApi extends BaseAPI {
    /**
     * Returns a paginated list of historical political events filtered by type, region, country, and time range.
     * @summary List of Historical Political Events.
     * @param {EventsApiV2EventsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public v2EventsGet(requestParameters: EventsApiV2EventsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return EventsApiFp(this.configuration).v2EventsGet(requestParameters.accept, requestParameters.page, requestParameters.pageSize, requestParameters.types, requestParameters.regions, requestParameters.countries, requestParameters.timeslotStart, requestParameters.timeslotEnd, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MetadataApi - axios parameter creator
 * @export
 */
export const MetadataApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a paginated list of country code values available for the `countries` filter.
         * @summary List available country code filter values.
         * @param {string} [accept] Default accept header
         * @param {number} [page] Page number (1-based index).
         * @param {number} [pageSize] Number of items per page.
         * @param {string} [q] Case-insensitive search query for country name or country code.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2MetadataCountryCodesGet: async (accept?: string, page?: number, pageSize?: number, q?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/metadata/country-codes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all event type values available for the `types` filter.
         * @summary List available event type filter values.
         * @param {string} [accept] Default accept header
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2MetadataEventTypesGet: async (accept?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/metadata/event-types`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all region values available for the `regions` filter.
         * @summary List available region filter values.
         * @param {string} [accept] Default accept header
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2MetadataRegionsGet: async (accept?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/metadata/regions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (accept != null) {
                localVarHeaderParameter['Accept'] = String(accept);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MetadataApi - functional programming interface
 * @export
 */
export const MetadataApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MetadataApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a paginated list of country code values available for the `countries` filter.
         * @summary List available country code filter values.
         * @param {string} [accept] Default accept header
         * @param {number} [page] Page number (1-based index).
         * @param {number} [pageSize] Number of items per page.
         * @param {string} [q] Case-insensitive search query for country name or country code.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2MetadataCountryCodesGet(accept?: string, page?: number, pageSize?: number, q?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CountryCodeMetadataListResponseBodyDef>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v2MetadataCountryCodesGet(accept, page, pageSize, q, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MetadataApi.v2MetadataCountryCodesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns all event type values available for the `types` filter.
         * @summary List available event type filter values.
         * @param {string} [accept] Default accept header
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2MetadataEventTypesGet(accept?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventTypeMetadataListResponseBodyDef>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v2MetadataEventTypesGet(accept, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MetadataApi.v2MetadataEventTypesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns all region values available for the `regions` filter.
         * @summary List available region filter values.
         * @param {string} [accept] Default accept header
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2MetadataRegionsGet(accept?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegionMetadataListResponseBodyDef>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v2MetadataRegionsGet(accept, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MetadataApi.v2MetadataRegionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MetadataApi - factory interface
 * @export
 */
export const MetadataApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MetadataApiFp(configuration)
    return {
        /**
         * Returns a paginated list of country code values available for the `countries` filter.
         * @summary List available country code filter values.
         * @param {MetadataApiV2MetadataCountryCodesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2MetadataCountryCodesGet(requestParameters: MetadataApiV2MetadataCountryCodesGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CountryCodeMetadataListResponseBodyDef> {
            return localVarFp.v2MetadataCountryCodesGet(requestParameters.accept, requestParameters.page, requestParameters.pageSize, requestParameters.q, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns all event type values available for the `types` filter.
         * @summary List available event type filter values.
         * @param {MetadataApiV2MetadataEventTypesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2MetadataEventTypesGet(requestParameters: MetadataApiV2MetadataEventTypesGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<EventTypeMetadataListResponseBodyDef> {
            return localVarFp.v2MetadataEventTypesGet(requestParameters.accept, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns all region values available for the `regions` filter.
         * @summary List available region filter values.
         * @param {MetadataApiV2MetadataRegionsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2MetadataRegionsGet(requestParameters: MetadataApiV2MetadataRegionsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<RegionMetadataListResponseBodyDef> {
            return localVarFp.v2MetadataRegionsGet(requestParameters.accept, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for v2MetadataCountryCodesGet operation in MetadataApi.
 * @export
 * @interface MetadataApiV2MetadataCountryCodesGetRequest
 */
export interface MetadataApiV2MetadataCountryCodesGetRequest {
    /**
     * Default accept header
     * @type {string}
     * @memberof MetadataApiV2MetadataCountryCodesGet
     */
    readonly accept?: string

    /**
     * Page number (1-based index).
     * @type {number}
     * @memberof MetadataApiV2MetadataCountryCodesGet
     */
    readonly page?: number

    /**
     * Number of items per page.
     * @type {number}
     * @memberof MetadataApiV2MetadataCountryCodesGet
     */
    readonly pageSize?: number

    /**
     * Case-insensitive search query for country name or country code.
     * @type {string}
     * @memberof MetadataApiV2MetadataCountryCodesGet
     */
    readonly q?: string
}

/**
 * Request parameters for v2MetadataEventTypesGet operation in MetadataApi.
 * @export
 * @interface MetadataApiV2MetadataEventTypesGetRequest
 */
export interface MetadataApiV2MetadataEventTypesGetRequest {
    /**
     * Default accept header
     * @type {string}
     * @memberof MetadataApiV2MetadataEventTypesGet
     */
    readonly accept?: string
}

/**
 * Request parameters for v2MetadataRegionsGet operation in MetadataApi.
 * @export
 * @interface MetadataApiV2MetadataRegionsGetRequest
 */
export interface MetadataApiV2MetadataRegionsGetRequest {
    /**
     * Default accept header
     * @type {string}
     * @memberof MetadataApiV2MetadataRegionsGet
     */
    readonly accept?: string
}

/**
 * MetadataApi - object-oriented interface
 * @export
 * @class MetadataApi
 * @extends {BaseAPI}
 */
export class MetadataApi extends BaseAPI {
    /**
     * Returns a paginated list of country code values available for the `countries` filter.
     * @summary List available country code filter values.
     * @param {MetadataApiV2MetadataCountryCodesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetadataApi
     */
    public v2MetadataCountryCodesGet(requestParameters: MetadataApiV2MetadataCountryCodesGetRequest = {}, options?: RawAxiosRequestConfig) {
        return MetadataApiFp(this.configuration).v2MetadataCountryCodesGet(requestParameters.accept, requestParameters.page, requestParameters.pageSize, requestParameters.q, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns all event type values available for the `types` filter.
     * @summary List available event type filter values.
     * @param {MetadataApiV2MetadataEventTypesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetadataApi
     */
    public v2MetadataEventTypesGet(requestParameters: MetadataApiV2MetadataEventTypesGetRequest = {}, options?: RawAxiosRequestConfig) {
        return MetadataApiFp(this.configuration).v2MetadataEventTypesGet(requestParameters.accept, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns all region values available for the `regions` filter.
     * @summary List available region filter values.
     * @param {MetadataApiV2MetadataRegionsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MetadataApi
     */
    public v2MetadataRegionsGet(requestParameters: MetadataApiV2MetadataRegionsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return MetadataApiFp(this.configuration).v2MetadataRegionsGet(requestParameters.accept, options).then((request) => request(this.axios, this.basePath));
    }
}



