/* tslint:disable */
/* eslint-disable */
/**
 * TempoGeoPolitical Map RESTful API
 * API for querying historical political events and metadata filter values.
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

